version: '3.3'
services: 
  mysqldev:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ankit
      - MYSQL_DATABASE=emp
      - MYSQL_PASSWORD=ankit
  web:
    build: .
    depends_on:
      - mysqldev
    ports:
      - 8090:8090
    environment:
      - DATABASE_HOST=mysqldev
      - DATABASE_USER=root
      - DATABASE_PASSWORD=ankit
      - DATABASE_NAME=emp  
      - DATABASE_PORT=3306
